apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit base application manifests
resources:
  - ../../base

# Target image rewrites for the private AWS ECR registry
images:
  - name: backend-app
    newName: YOUR_AWS_ACCOUNT_ID.dkr.ecr.eu-south-2.amazonaws.com/backend-app
    newTag: v1.0.0
  - name: frontend-app
    newName: YOUR_AWS_ACCOUNT_ID.dkr.ecr.eu-south-2.amazonaws.com/frontend-app
    newTag: v1.0.0